#!/usr/bin/env sh

chown -R exosuite:www-data ${APP_DIR}

find  ${APP_DIR} -type f -exec chmod 644 {} \;
find  ${APP_DIR} -type d -exec chmod 755 {} \;

chgrp -R www-data ${APP_DIR}/storage ${APP_DIR}/bootstrap/cache
chmod -R ug+rwx ${APP_DIR}/storage ${APP_DIR}/bootstrap/cache

cd ${APP_DIR}

rm bootstrap/cache/*.php
php artisan optimize:clear
php artisan package:discover
php artisan config:cache
php artisan route:cache
php artisan view:cache

for command in "$@"
do
    php artisan command
done